@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkphbmUgRG9lIiwiaXNzIjoiY2xvdWRkaXNrLWRlbW8iLCJleHAiOjE3NDY1MjUwNzEsIm5iZiI6MTc0NjQzODY3MSwiaWF0IjoxNzQ2NDM4NjcxfQ.0N5tw2qHtDPGEy-sn9K7zzBzJ2epCee1QuWwzZnETzw


###
POST http://127.0.0.1:8080/file/file HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkphbmUgRG9lIiwiaXNzIjoiY2xvdWRkaXNrLWRlbW8iLCJleHAiOjE3NDU0NjI2NzEsIm5iZiI6MTc0NTM3NjI3MSwiaWF0IjoxNzQ1Mzc2MjcxfQ.hQ3ojAkERWX2vVUPeXast5xLYIBmDe9s-NnXuEaa7kQ

{
	"username": "Jane Doe",
	"password": "123456789",
	"email": "test@123.com"
}

### 文件上传

POST http://127.0.0.1:8080/file/upload HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkphbmUgRG9lIiwiaXNzIjoiY2xvdWRkaXNrLWRlbW8iLCJleHAiOjE3NDU1Njk3NTUsIm5iZiI6MTc0NTQ4MzM1NSwiaWF0IjoxNzQ1NDgzMzU1fQ.eropawMgOchjWYWOIv3KQJMH0GRbo5YRZC2oHQ23ReA
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="filename"

title3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="path"

/tmp2/
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 查询目录下文件 

# POST http://127.0.0.1:8080/file/files HTTP/1.1
POST http://103.91.209.53:31866/file/files HTTP/1.1
Content-Type: application/json
Authorization: {{token}} 

{
	"path": "tmp2"
}

### 删除文件

POST http://127.0.0.1:8080/file/delete HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"filenames": [
		"tmp3"
	]
}


### 修改文件名
POST http://127.0.0.1:8080/file/modify HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"fileinfos": [
		{
			"srcname": "tmp2/background.jpg", 
			"dstname": "tmp2/background2.jpg"
		},
		{
			"srcname": "tmp2/title3",
			"dstname": "tmp2/title"
		}
	]
}


### 移动文件
POST http://127.0.0.1:8080/file/move HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"fileinfos": [
		{
			"srcname": "tmp2/background2.jpg", 
			"dstname": "tmp/background2.jpg"
		}
	]
}

### 文件下载
# POST http://103.91.209.53:31866/file/download HTTP/1.1
POST http://127.0.0.1:31866/file/download HTTP/1.1
Content-Type: application/json
Authorization: {{token}} 

{
	"path": "tmp/background2.jpg"
}